export const REQ_TEACHER_DATA = "REQ_TEACHER_DATA";
export const GET_TEACHER_DATA = "GET_TEACHER_DATA";
export const REQ_TEACHER_DATA_FAILED = "REQ_TEACHER_DATA_FAILED";

export const REQ_CLASS_DATA = "REQ_CLASS_DATA";
export const GET_CLASS_DATA = "GET_CLASS_DATA";
export const REQ_CLASS_DATA_FAILED = "REQ_CLASS_DATA_FAILED";


export const SIGNUP_LOADING = "SIGNUP_LOADING";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";


export const LOGOUT = "LOGOUT"